version: '3.8'
services:
  app:
    container_name: products_app
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge