version: '3'
services:
  app:
    container_name: products_app
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Reemplaza 8080 con el puerto en el que está corriendo tu aplicación
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true