
services:
    app:
      container_name: products_app
      build:
        context: '.'
        dockerfile: Dockerfile
      environment:
        - 'POSTGRES_USER=myuser'
        - 'POSTGRES_PASSWORD=secret'
        - 'PGHOST=192.168.100.244'
        - 'PGPORT=5432'
        - 'PGDATABASE=contable'
      ports:
        - 8080:8080
      depends_on:
        - postgres
    postgres:
      container_name: product_db
      image: 'postgres:latest'
      environment:
        - 'POSTGRES_DB=elctronica'
        - 'POSTGRES_PASSWORD=secret'
        - 'POSTGRES_USER=myuser'
      ports:
        - '5432:5432'