version: '3'
services:
  app:
    container_name: products_app
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true